"""empty message

Revision ID: 6e9f8dee345d
Revises: 
Create Date: 2025-07-26 15:38:49.162554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9f8dee345d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('contest',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('createdon', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('point_per_proofread', sa.SmallInteger(), nullable=True),
    sa.Column('point_per_validate', sa.SmallInteger(), nullable=True),
    sa.Column('lang', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('contest_admin',
    sa.Column('user_name', sa.String(length=190), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('jury',
    sa.Column('user_name', sa.String(length=190), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('user',
    sa.Column('user_name', sa.String(length=190), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('association_table',
    sa.Column('contest_cid', sa.Integer(), nullable=True),
    sa.Column('contest_admin_user_name', sa.String(length=190), nullable=True),
    sa.ForeignKeyConstraint(['contest_admin_user_name'], ['contest_admin.user_name'], ),
    sa.ForeignKeyConstraint(['contest_cid'], ['contest.cid'], )
    )
    op.create_table('book_contest_association_table',
    sa.Column('contest_cid', sa.Integer(), nullable=True),
    sa.Column('book_name', sa.String(length=190), nullable=True),
    sa.ForeignKeyConstraint(['book_name'], ['book.name'], ),
    sa.ForeignKeyConstraint(['contest_cid'], ['contest.cid'], )
    )
    op.create_table('index_page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_name', sa.String(length=190), nullable=False),
    sa.Column('book_name', sa.String(length=190), nullable=True),
    sa.Column('validator_username', sa.String(length=190), nullable=True),
    sa.Column('proofreader_username', sa.String(length=190), nullable=True),
    sa.Column('validate_time', sa.DateTime(), nullable=True),
    sa.Column('proofread_time', sa.DateTime(), nullable=True),
    sa.Column('v_revision_id', sa.Integer(), nullable=True),
    sa.Column('p_revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_name'], ['book.name'], ),
    sa.ForeignKeyConstraint(['proofreader_username'], ['user.user_name'], ),
    sa.ForeignKeyConstraint(['validator_username'], ['user.user_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jury_association_table',
    sa.Column('contest_cid', sa.Integer(), nullable=True),
    sa.Column('jury_user_name', sa.String(length=190), nullable=True),
    sa.ForeignKeyConstraint(['contest_cid'], ['contest.cid'], ),
    sa.ForeignKeyConstraint(['jury_user_name'], ['jury.user_name'], )
    )
    op.create_table('user_contest_association_table',
    sa.Column('contest_cid', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=190), nullable=True),
    sa.ForeignKeyConstraint(['contest_cid'], ['contest.cid'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], )
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=190), nullable=False),
    sa.Column('review_text', sa.String(length=500), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['index_page.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.user_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('user_contest_association_table')
    op.drop_table('jury_association_table')
    op.drop_table('index_page')
    op.drop_table('book_contest_association_table')
    op.drop_table('association_table')
    op.drop_table('user')
    op.drop_table('jury')
    op.drop_table('contest_admin')
    op.drop_table('contest')
    op.drop_table('book')
    # ### end Alembic commands ###
